services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_DB: "cardtrader"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  data: